name: Build EXE on Windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências do requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Instalar PyInstaller
      run: pip install pyinstaller

    - name: Gerar .exe
      run: pyinstaller --onefile main.py

    - name: Salvar EXE como artefato
      uses: actions/upload-artifact@v4
      with:
        name: app-windows
        path: dist/main.exe
